language: node_js
node_js:
- '6'
dist: trusty
before_install: |
    set -ev
    set -o pipefail
    npm install -g npm
    ls -l ./_scripts
    chmod +x ./_scripts/*.sh
    ls -l ./_scripts
script:  npm run test
after_failure: |
    tail -n +1 -- /home/travis/.npm/_logs/*-debug.log
sudo: false
#notifications:
