language: node_js
node_js:
- '6'
dist: trusty
before_install: |
    set -ev
    set -o pipefail
#install: ./_scripts/setup.sh
script:  ./_scripts/test.sh
after_failure: |
    tail -n +1 -- /home/travis/.npm/_logs/*-debug.log
sudo: false
#notifications:
