name: RomanArabic-PR-workflow

on:
  push:
    branches:  [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup | Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Setup | go
        uses: actions/setup-go@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: just build-all
      - run: just test-all
